spring:
  jpa:
    hibernate:
      ddl-auto: update
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://127.0.0.1:3306/
      username: root
      password: 123456
      max-active: 20
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM dual
      initial-size: 1
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      filter:
        stat:
          enabled: true
        wall:
          enabled: true
          db-type: mariadb
          config:
            truncate-allow: false
            drop-table-allow: false
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        login-username: druid
        login-password: druid
        enabled: true


